[workspace]
channels = ["https://repo.prefix.dev/max-nightly", "conda-forge"]
name = "mojo-json"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025061222,<26"
